spring:
  datasource:
    url: jdbc:h2:mem:testDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth

#  devtools:
#    livereload:
#      enabled: false
#
#    restart:
#      enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG