spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rss_feeder
    driverClassName: org.postgresql.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379


#  devtools:
#    livereload:
#      enabled: false
#
#    restart:
#      enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG