spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rss_feeder
    driverClassName: org.postgresql.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
      springframework:
        security: DEBUG
    root: info